In [ ]:
# Problem Set 6: Simulating robots
# Name:
# Collaborators:
# Time:

In [21]:
# setup notebook
%matplotlib inline
%autoreload 2
import matplotlib.pyplot as plt
import numpy as np


## Test if matplotlib / numpy is installed and working
Run the following cell.  You should see a plot pop up.

In [ ]:
%run ps6_pkgtest.py

In [16]:
# Problem 1: Simple (not comprehensive) tests - add any others you find useful
import ps6
room = ps6.RectangularRoom(3,4)
print(room.isTileCleaned(2,3))
print(room.getNumTiles())
print(room.getNumCleanedTiles())

False
12
0


In [24]:
# Problem 1: simple (not comprehensive) tests for Robot
#  add any you find useful
import ps6
robot = ps6.Robot(room, 1)
robot.getRobotPosition().x

2

In [42]:
# Problem 2 test
# write a test that builds a room, displays all the tile clean statuses, 
# runs StandardRobot one timestep, and displays all the tiles again

# add other tests you might want here too.





In [46]:
room = ps6.RectangularRoom(10,10)
robot = ps6.StandardRobot(room,5)
for i in range(5):
    robot.updatePositionAndClean()
print(room.getNumCleanedTiles()/room.getNumTiles())

0.25


In [66]:
# Problem 3 test

ps6.runSimulation(num_robots=2, speed=5, width=10, height=10, 
    min_coverage=0.9, num_trials=10, robot_type=ps6.StandardRobot)
# You may or may not use debug print statements, one example is shown

# check your simulation against some of the values given in the PS6 writeup

debug: steps each trial: array([ 39.,  45.,  36.,  36.,  39.,  34.,  28.,  60.,  39.,  32.])


38.799999999999997

In [ ]:
# problem 4 output
import ps6
import seaborn as sns
ps6.showPlot1() 

In [ ]:
# problem 4, part 2
import ps6
ps6.showPlot2() 

## Some syntax testing I did that you may find useful
Put your own one-liner tests in here.

In [9]:
np.ones((3,3)).ravel()

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
np.ones((3,3)) == 1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [25]:
int(np.random.rand()*3)  # lots of ways to do this

0

In [29]:
np.r_[0:4]

array([0, 1, 2, 3])

In [32]:
for (a,b) in zip([1,2,3],[3,4,9]):
    print ('a: %d, b: %d' % (a,b))

a: 1, b: 3
a: 2, b: 4
a: 3, b: 9
